In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from model import SimpleNN, HyperParams
from data import load_data
import config as m_config

In [2]:
config = m_config.get_default_config()

In [3]:
train_loader, val_loader = load_data()

In [4]:
train_loader.dataset.data

[(array([0.272763  , 0.269004  , 0.26210016, 0.27291048, 0.28246778,
         0.28023195, 0.2720014 , 0.2555895 , 0.27170658, 0.26760358,
         0.26743156, 0.2767923 , 0.29507148, 0.2889048 , 0.27743107,
         0.24728519, 0.2440421 , 0.26406568, 0.23893178, 0.28514576,
         0.17625672, 0.14544737, 0.1498698 , 0.1461845 , 0.16618347,
         0.18212861, 0.18161273, 0.18387306, 0.15306371, 0.17259598],
        dtype=float32),
  array([[1]], dtype=int64)),
 (array([0.269004  , 0.26210016, 0.27291048, 0.28246778, 0.28023195,
         0.2720014 , 0.2555895 , 0.27170658, 0.26760358, 0.26743156,
         0.2767923 , 0.29507148, 0.2889048 , 0.27743107, 0.24728519,
         0.2440421 , 0.26406568, 0.23893178, 0.28514576, 0.17625672,
         0.14544737, 0.1498698 , 0.1461845 , 0.16618347, 0.18212861,
         0.18161273, 0.18387306, 0.15306371, 0.17259598, 0.17296451],
        dtype=float32),
  array([[0]], dtype=int64)),
 (array([0.26210016, 0.27291048, 0.28246778, 0.28023195, 0.272

In [5]:
hparams = HyperParams()

In [6]:
# Initialize the model, loss function, and optimizer
model = SimpleNN(config, params=hparams)
model.setup_criterion()
model.initialize_from_ckp()

In [11]:
model.fit(train_loader, val_loader)

Epoch 1/100, Train Loss: 0.7222, Val Loss: 0.6830, Val Accuracy: 0.5333
Epoch 2/100, Train Loss: 0.7029, Val Loss: 0.6836, Val Accuracy: 0.5333
Epoch 3/100, Train Loss: 0.7177, Val Loss: 0.6835, Val Accuracy: 0.5333
Epoch 4/100, Train Loss: 0.7128, Val Loss: 0.6839, Val Accuracy: 0.5333
Epoch 5/100, Train Loss: 0.7204, Val Loss: 0.6833, Val Accuracy: 0.5333
Epoch 6/100, Train Loss: 0.7089, Val Loss: 0.6815, Val Accuracy: 0.5667
Epoch 7/100, Train Loss: 0.7148, Val Loss: 0.6811, Val Accuracy: 0.5667
Epoch 8/100, Train Loss: 0.7044, Val Loss: 0.6816, Val Accuracy: 0.5667
Epoch 9/100, Train Loss: 0.7324, Val Loss: 0.6817, Val Accuracy: 0.5500
Epoch 10/100, Train Loss: 0.7100, Val Loss: 0.6807, Val Accuracy: 0.5667
Epoch 11/100, Train Loss: 0.6975, Val Loss: 0.6818, Val Accuracy: 0.5500
Epoch 12/100, Train Loss: 0.7289, Val Loss: 0.6825, Val Accuracy: 0.5333
Epoch 13/100, Train Loss: 0.7015, Val Loss: 0.6816, Val Accuracy: 0.5500
Epoch 14/100, Train Loss: 0.7173, Val Loss: 0.6816, Val Accu

In [8]:
best_model.eval()
val_loss = 0.0
correct = 0
total = 0
with torch.no_grad():
    for X_etc, X_emb, Y in val_loader:
        outputs = best_model(X_etc, X_emb)
        loss = criterion(outputs, Y)
        _, predicted = torch.max(F.softmax(outputs, dim=1), 1)
        total += Y.size(0)
        correct += (predicted == Y).sum().item()

val_accuracy = correct / total

print(f'Val Accuracy: {val_accuracy:.4f}')

NameError: name 'best_model' is not defined